config = {
        "model_name": "microsoft/codebert-base",
        "sven_data_path": "/home/vkist/Downloads/MSR_data_cleaned_json/code_bert/train.json",
        "big_vul_data_path": "/home/vkist/Downloads/MSR_data_cleaned_json/code_bert/MSR_data_cleaned.csv",
        "output_dir": "./meta_learning_vul_model",
        "max_length": 512,
        "batch_size": 4,            
        "inner_lr": 0.01,           
        "outer_lr": 0.0005,          
        "ft_lr": 2e-5,              
        "num_inner_steps": 4,        
        "meta_batch_size": 2,        
        "n_meta_tasks": 30,         
        "k_shot": 6,                 
        "big_vul_sample_size": 10000, 
        "meta_epochs": 3,           
        "ft_epochs": 10,             
        "seed": 42,
        "warmup_ratio": 0.1,         
        "weight_decay": 0.01,        
        "early_stopping_patience": 5, 
        "class_weights": [0.5, 0.5],
        "use_vulnerability_type_matching": True  # Enable matching by vulnerability type
    }